global:
  scrape_interval: 60s  # Colects each 60 seconds

scrape_configs:
  - job_name: 'python_metrics'
    static_configs:
      - targets: ['host.docker.internal:3030']  # Seu script Python
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
